version: '3'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
       - 8001:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: root
    networks:
       - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
    networks:
       - back
  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
       - 8080:80
    environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: root
    networks:
       - back
  webserver:
    depends_on:
       - wordpress
    image: httpd:2.4
    restart: always
    ports:
      - 8000:80
    volumes:
      - /path/to/app:/app
    networks:
      - back
networks:
  back:
volumes:
  db_data:  
