version: '2'
services:
  wordpress:
    build: .
    depends_on:
       - db
    restart: always
    ports:
       - 8001:80
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: root
    networks:
       - back
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
    networks:
       - back
  webserver:
    depends_on:
       - wordpress
    image: apache2
    restart: always
    ports:
      - 8000:80
    volumes:
      - /path/to/app:/app
    networks:
      - back
networks:
  back:
volumes:
  db_data:  
