version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: root
       MYSQL_PASSWORD: root
    networks:
       - back
  phpmyadmin:
    depends_on:
       - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
       - 8080:80
    environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: root
    networks:
       - back
  web:
    build: .
    depends_on:
       - db
    restart: always
    ports:
       - 8006:80
    volumes:
      - ./wp-app:/var/www/html
      
    networks:
       - back
networks:
  back:
volumes:
  db_data:  

